mousy/models.py
import datetime
from django.db import models
from django.contrib.auth.models import User

class UserReceiptManager(models.Manager):
    def for_user(self, user):
        return self.get_query_set().filter(created_by=user)

class Receipt(models.Model):
    #Core fields
    date = models.DateField(blank = False)
    #amount = models.DecimalField(max_digits = 6, decimal_places = 2, blank = False)
    amount = models.FloatField(blank=False)
    detail = models.CharField(max_length = 250, blank = False)
    name = models.CharField(max_length = 250, blank = False)
    created_by = models.ForeignKey(User)
    
    #Auto populated 
    created = models.DateTimeField(auto_now_add = True)

    objects = models.Manager()
    user_objects = UserReceiptManager()

    class Meta:
        verbose_name_plural = "Receipts"
        ordering = ['-created']
    
    def __unicode__(self):
        return self.detail    
    
    def save(self, force_insert = False, force_update = False):
        super(Receipt, self).save(force_insert, force_update)
    
    def as_dict(self):
        return {'amount':self.amount,
                'detail':self.detail,
                'created_by':self.created_by.username,                
                'date':self.date.strftime("%Y-%b-%d"),
                'name':self.name,
                'pk':self.pk
               }
        
    @models.permalink    
    def get_absolute_url(self):
        return ('mousy_receipt_detail', (), {'year':  self.date.strftime("%Y"),
                                             'month': self.date.strftime("%b").lower(),
                                             'day': self.date.strftime("%d"),
                                             'pk': self.pk})




    
    
    
        

mousy/forms.py
import logging

from django import forms
from django.contrib.auth.admin import User

from mousy.models import Receipt 

class ReceiptForm(forms.ModelForm):
    class Meta:
        model = Receipt
        exclude = ('created_by',)
   
   
class LoginForm(forms.Form):
    username = forms.CharField(max_length = 30)
    password = forms.CharField(max_length = 30,
                               widget = forms.PasswordInput(render_value = False))
        
    def clean(self):
        if 'username' in self.cleaned_data and 'password' in self.cleaned_data:
            try:
                User.objects.get(username = self.cleaned_data['username'],
                                 password = self.cleaned_data['password'])
            except User.DoesNotExist:
                raise forms.ValidationError("User does not exist")            
        return self.cleaned_data 
        

        
    

mousy/views.py
import logging

from django.contrib.auth.decorators import login_required
from django.template import RequestContext
from django.contrib.auth.admin import User
from django.views.generic.edit import CreateView, UpdateView, DeleteView


from django.contrib.auth.admin import User
from django.contrib.auth.forms import UserCreationForm
  
def user_signup(request):
    if request.method == 'POST':
        form = UserCreationForm(data = request.POST)
        
        if form.is_valid():
            new_user = form.save()
            new_user = authenticate(username = request.POST['username'],
                                    password = request.POST['password1'])
            if new_user is not None:
                login(request, new_user)
                return HttpResponseRedirect("/")        
    else:        
        form = UserCreationForm()
    return render_to_response('accounts/signup_form.html',
                                { 'form': form },
                                context_instance = RequestContext(request))

###Signup user
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.contrib.auth import login, authenticate
from mousy.forms import LoginForm

def user_login(request):
    if request.method == 'POST':
        form = LoginForm(data = request.POST)
        usernm = request.POST['username']
        passwd = request.POST['password']
        user = authenticate(username = usernm, password = passwd)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect("/household")        
    else:        
        form = LoginForm()
    return render_to_response('accounts/login_form.html',
                                { 'form': form },
                                context_instance = RequestContext(request))
        
        
from django.contrib.auth import logout
def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/users/login/')
            

###create, modify, and delete Receipts
from mousy.forms import ReceiptForm
from mousy.models import Receipt

class ReceiptCreate(CreateView):
    form_class = ReceiptForm
    model = Receipt
    success_url = "/household"
    template_name = "household/receipt_form.html"

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super(ReceiptCreate, self).form_valid(form)

class ReceiptUpdate(UpdateView):
     form_class = ReceiptForm
     model = Receipt
     template_name = 'household/receipt_form.html'
    
class ReceiptDelete(DeleteView):
    form_class = ReceiptForm
    model = Receipt
    template_name = 'household/receipt_confirm_delete.html'
    success_url = "/household"



###Return JSON receipts
from django.http import HttpResponse
from django.utils import simplejson
from django.views.generic.detail import View, BaseDetailView, SingleObjectTemplateResponseMixin
from django.views.generic.list import ListView, MultipleObjectTemplateResponseMixin

class JSONResponseMixin(object):
    def render_to_response(self, context):
        return self.get_json_response(self.convert_context_to_json(context))
    def get_json_response(self, content, **httpresponse_kwargs):
        return HttpResponse(content, content_type='application/json', **httpresponse_kwargs)
    def convert_context_to_json(self, context):
        return simplejson.dumps(context)

class HybridListView(JSONResponseMixin, ListView):
    def render_to_response(self, context):
        current_user = self.request.user
        if self.request.is_ajax():
            context['object_list'] = Receipt.user_objects.for_user(current_user)
            o_list = context['object_list']
            j_list = [o.as_dict() for o in o_list]
            return JSONResponseMixin.render_to_response(self, j_list)
        return MultipleObjectTemplateResponseMixin.render_to_response(self, context)


class HybridDetailView(JSONResponseMixin, SingleObjectTemplateResponseMixin, BaseDetailView):
    def render_to_response(self, context):
        if self.request.is_ajax():
            logging.error("Ajax Request Logged")
            obj = context['object'].as_dict()
            return JSONResponseMixin.render_to_response(self, obj)
        else:
            return SingleObjectTemplateResponseMixin.render_to_response(self, context)

sites/mousy/main.py
#! /usr/bin/env python
import os
import tornado.httpserver
import tornado.ioloop
import tornado.wsgi
import tornado.web
import sys
import django.core.handlers.wsgi
import logging

APP_NAME = "mousy"

APP_DIR = os.path.abspath(os.path.dirname(__file__)) 
SITE_DIR = os.path.abspath(os.path.join(APP_DIR, "..")) 
PARENT_DIR = os.path.abspath(os.path.join(SITE_DIR, "..")) 
STATIC_PATH = os.path.abspath(os.path.join(PARENT_DIR, "static"))
#logging.error(STATIC_PATH)

from tornado.options import define, options
define("port", default=9000, help="run on the given port", type=int)

def main():
    ENVIRON_MODULE = ".".join(["config.settings", APP_NAME])
    
    tornado.options.parse_command_line()
        
    os.environ['DJANGO_SETTINGS_MODULE'] = ENVIRON_MODULE 
    wsgi_app = tornado.wsgi.WSGIContainer(django.core.handlers.wsgi.WSGIHandler())
    
    application = tornado.web.Application([
            (r"/static/(.*)", tornado.web.StaticFileHandler, {"path": STATIC_PATH}),
            (r".*", tornado.web.FallbackHandler, dict(fallback=wsgi_app)),
        ])
    
    server = tornado.httpserver.HTTPServer(application)
    server.listen(options.port)
    tornado.ioloop.IOLoop.instance().start()

if __name__ == "__main__":
    main()
    
   
    

templates/accounts/login_form.html
{% extends "mousy/base.html" %}
{% block title %} | {{ title }}{% endblock title %}

{% block content %}

    <form action="" method="POST">{% csrf_token %}
        <table id="user-login">
            <colgroup>
                <col class="label"/>
                <col class="field"/>                
                <col class="errors"/>                
            </colgroup>            
            <thead>
                 <tr>
                     <th scope="col">Label</th>
                     <th scope="col">Field</th>
                     <th scope="col"></th>                     
                 </tr>
            </thead>
            {% for field in form %}
            <tr>
                <td>{{ field.label_tag }}</td>
                <td>{{ field }}</td>
                <td>
                    {{ field.errors }}                    
                </td>                
            </tr>
            {% endfor %}         
            <tr>
                <td></td>
                <td></td>
                <td>{{ form.non_field_errors }}</td>
            </tr>
            <tr>
                <td><input id="login-button" type="submit" value="Submit" /></td>
            </tr>
        </table>
        
    </form>

{% endblock content %}

templates/accounts/profile.html
{% extends "mousy/base.html" %}
{% block title %} | User Profile{% endblock title %}
{% block head %}    
{% endblock head %}
{% block content %}

    <p>User Profile</p>
    
    <table>
        <tbody>
            <tr>
                <td>Username:</td>
                <td>{{ user.username }}</td>
            </tr>
            <tr>
                <td>email:</td>
                <td>{{ user.email }}</td>
            </tr>
        </tbody>
    </table>
    
{% endblock content %}

templates/accounts/signup_form.html
{% extends 'mousy/base.html' %}
{% block title %} | {{ title }}{% endblock title %}

{% block content %}
    <h3>Register for your new account</h3>
    <p>All fields required</p>
    <form action="" method="POST">{% csrf_token %}
        <table id="user-signup">
            <colgroup>
                <col class="label"/>
                <col class="field"/>                
                <col class="errors"/>                
            </colgroup>            
            <thead>
                 <tr>
                     <th scope="col">Label</th>
                     <th scope="col">Field</th>
                     <th scope="col">Errors</th>                     
                 </tr>
            </thead>
            {% for field in form %}
            <tr>
                <td>{{ field.label_tag }}</td>
                <td>{{ field }}</td>
                <td>{{ field.errors }}</td>
            </tr>
            {% endfor %}
            <tr>
                <td><input id="signup-button" type="submit" value="Submit" /></td>
            </tr>
        </table>
        
    </form>

{% endblock content %}

templates/household/household.html
{% extends 'mousy/base.html' %}
{% block head %}
    
    <title>Mousy{% block title %} | {{ title }}{% endblock title %}</title>
 
    <!-- third-party javascript -->
    <script src="/static/mousy/js/crossfilter.js"></script>
    <script src="/static/mousy/js/dc.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js"></script>
    
    <!-- third-party stylesheets -->
    <link rel="stylesheet" type="text/css"  href="/static/mousy/css/dc.css" />
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css"  />
  
    <!-- our javascript -->
    <script src="/static/mousy/js/household.js"></script>        

    <script>
        $(function () { household.initModule( $('#main-container') ); });
    </script>
{% endblock head %}

{% block content %}     

    <div id="sidebar">		
        {% if user.is_authenticated %}  
            User: {{ user.username }} (<a href="{% url 'mousy_users_logout' %}">Logout</a>)
                {% if perms.mousy.add_receipt %}
                    <span id="sidebar-add-receipt">---<a id="add-receipt" href="/household/receipt/add/">  Add receipt</a></span>
                {% endif %}
      {% else %}
              <p>
                  <a href="{% url 'mousy_users_login' %}">Login</a>
                  <span>&nbsp;or&nbsp;</span>
                  <a href="{% url 'mousy_users_signup' %}">Sign&nbspUp</a>	
              </p>		    
        {% endif %}
    </div>    
    <div class='container' id='main-container'></div>    
    
{% endblock content %}

templates/household/receipt_archive.html
{% extends "mousy/base.html" %}

{% block title %} {{ block.super }} | Latest Receipts {% endblock title %}  

{% block content %}

{% for object in page_obj.object_list %}
    <h3 class="title"><a class="title" href="{{ object.get_absolute_url }}">Receipt ID: {{ object.pk }}</a></h3>
    <p>
          Created by: {{ object.created_by }}<br>
          Date: {{ object.date | date:"F j, Y" }}<br>
          Details: {{ object.detail }} <br>
          Amount: ${{ object.amount }}	
    </p>
    <br> 
{% endfor%}


{% if is_paginated %}
    <div class="pagination">
	<span class="page-links">
	{% for page_num in paginator.page_range %}
	    {% if page_obj.number == page_num %}
		{{page_obj.number}}
	    {% else %}
		<a class="page-links" href='{% url "mousy_receipt_archive_index" %}?page={{ page_num }}'>{{ page_num }}</a>
	    {% endif %}                    
	{% endfor %}
	</span>
    </div>
    <br>
{% endif %}
    
{% endblock content %}

templates/household/receipt_archive_day.html
{% extends "household/receipt_archive.html" %}

{% block title %} {{ block.super }} | {{ month| date:"M Y"}} {% endblock title %}  

{% block content %}

	<h3>Receipts logged on {{ day| date:"F j, Y"}} </h3>
	
	{{ block.super }}
	
{% endblock content %}

templates/household/receipt_archive_month.html
{% extends "mousy/base.html" %}

{% block title %} {{ block.super }} | {{ month| date:"M Y"}} {% endblock title %}  

{% block content %}

	<h3 class="title">Receipts logged in  {{ month| date:"M-Y"}} </h3>
	<ul class="date-list">
		{% for date in date_list %}
			<li>
				<a href="{% url 'mousy_receipt_archive_month' date|date:'Y' date|date:'b' %}{{ date|date:'j'}}/">{{ date|date:'j'}}</a>
			</li>
		{% endfor %}
	</ul>
	
	{{ block.super }}
	
{% endblock content %}

templates/household/receipt_archive_year.html
{% extends "mousy/base.html" %}

{% block title %} {{ block.super }} | {{ year.year }} {% endblock title %}  

{% block content %}

	<h3 class="title">Receipts logged in {{ year| date:"Y"}} </h3>
	<ul>		
	{% for date in date_list %}
		<li>
			<a href="{% url 'mousy_receipt_archive_year' date|date:'Y' %}{{ date|date:'b'}}/">{{ date|date:'F'}}</a>
			
		</li>		
	{% endfor %}
	</ul>    
{% endblock content %}

templates/household/receipt_confirm_delete.html
{% extends 'mousy/base.html' %}
{% block title %} | {{ title }}{% endblock title %}
{% block head %}
{% endblock head %}

{% block content%}       
  <h3>Delete receipt</h3>

  {% if perms.mousy.delete_receipt %}
    <h4 class="title">Receipt No. {{ object.pk }}</h4>
    <p>
      Created by: {{ object.created_by }}<br>
      Date: {{ object.date | date:"F j, Y" }}<br>
      Details: {{ object.detail }} <br>
      Amount: ${{ object.amount }}
    </p>
    <form method="POST" action="{% url 'mousy_receipt_delete' object.pk %}">{% csrf_token %}
      <input type="submit" name="confirm-delete" value="Confirm Delete">
    </form>
  {% else %}
    <p>Unauthorized<a href="{% url 'mousy_household' %}">Back</a></p>
  {% endif %}

{% endblock content %}

templates/household/receipt_detail.html
{% extends "mousy/base.html" %}

{% block content %}
     <h4 class="title">Receipt No. {{ object.pk }}</h4>
     <p>
          Created by: {{ object.created_by }}<br>
          Date: {{ object.date | date:"F j, Y" }}<br>
          Details: {{ object.detail }} <br>
          Amount: ${{ object.amount }}<br>
          Name: {{ object.name }}          
     </p>    
     
{% endblock content %}

templates/household/receipt_form.html
{% extends 'mousy/base.html' %}
{% block title %} | {{ title }}{% endblock title %}
{% block head %}
{% endblock head %}

{% block content%}
       
    <h3>Add receipt (Date format: YYYY-MM-DD)</h3>
    
    <form action="" method="POST">{% csrf_token %}	
	<table id="receipt-table">
	    {{ form.as_table }}
	</table>		
	<input type="submit" value="Submit"/>
    </form>
    
{% endblock content %}

templates/mousy/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="author" content="jvwong" />
            
    <!-- Add d3 library -->
    <script src="http://d3js.org/d3.v3.min.js" charset="utf-8"></script>      
    <script type="text/javascript" src="/static/mousy/js/d3.legend.js"></script>
               
    <!-- Add jQuery library -->
    <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
    <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
        
    <link rel="stylesheet" type="text/css" href="/static/mousy/css/base.css">
        
    <title>Mousy{% block title %}{% endblock title %}</title>

    {% block head %}
    {% endblock head %}
</head>

<body>
    <div id="header">
	    
      {% block navigation %}
      <div id="navigation">
	    
        <div id="nav-links">
          {% block navLinks %}
              <div class="navlink"><a href = "{% url 'mousy_economie' %}">Economie</a></div>
              <div class="navlink"><a href = "{% url 'mousy_household' %}">Household</a></div>
              <div class="navlink"><a href = "{% url 'mousy_contact' %}">Contact</a></div>
              <div class="navlink"><a href = "{% url 'admin:index' %}">Admin</a></div>
          {% endblock navLinks %}
        </div>
	    
      </div>
      {% endblock navigation %}

    </div>  

 	
    <div id="content">
	    {% block content %}
	    {% endblock content %}   
    </div>

</body>
</html>

templates/mousy/contact.html
{% extends 'mousy/base.html' %}
{% block title %} | {{ title }}{% endblock title %}
{% block head %}    
{% endblock head %}

{% block content %}
<div id='contact-details'>
  <h2>Jeffrey V Wong, Ph.D.</h2>
  
  <p>
    2285 Bur Oak Avenue<br>
    Unit 69<br>
    Markham ON CAN<br>
    L6E 0B9<br>
    <br>
    tel: 647 886 0781 (mobile), 905 554 0781 (home)<br>
    email: jvwong [at] gmail [dot] com<br>
    web: <a href="http://www.jeffreyvwong.ca">www.jeffreyvwong.ca</a> 
  </p>
</div>
{% endblock content %}

templates/mousy/economie.html
{% extends 'mousy/base.html' %}
{% block title %} | {{ title }}{% endblock title %}
{% block head %}
    <script type="text/javascript" src="static/mousy/js/economie.js"></script>
{% endblock head %}

{% block content %}
<div id="rent-buy-container">
     <h2 id="page-title">The eternal buy-vs-rent debate</h3>
     
     <div id="parameters">
          <fieldset>
               <legend>Parameters</legend>
                    <label for="horizon">Horizon:</label>
                    <input class="slider-text" type="text" id="horizon" size="8" />
                    <div id="horizon_slider"></div><br>
                    
                    <hr>
                         
                    <label for="purchase_price">Purchase Price:</label>
                    <!--<input type="text" name="purchase_price_value" id="purchase_price" value="750000" />-->
                    <input class="slider-text" type="text" id="purchase_price" size="8" />
                    <div id="purchase_price_slider"></div><br>
                    
                    <label for="downpayment">Downpayment:</label>
                    <input class="slider-text" type="text" id="downpayment" size="10" />
                    <div id="downpayment_slider"></div><br>
                                        
                    <label for="interest_rate">Interest rate</label>
                    <input class="slider-text" type="text" id="interest_rate" size="8" />
                    <div id="interest_rate_slider"></div><br>
                    
                    <label for="amortization">Amortization</label>
                    <input class="slider-text" type="text" id="amortization" size="8" />
                    <div id="amortization_slider"></div><br>
                    
                    <label for="property_tax_rate">Property tax</label>
                    <input class="slider-text" type="text" id="property_tax_rate" size="8" />
                    <div id="property_tax_rate_slider"></div><br>
                    
                    <label for="maintainance">Annual maintainance</label>
                    <input class="slider-text" type="text" id="maintainance" size="6" />
                    <div id="maintainance_slider"></div><br>
                    
                    <label for="dues">Annual dues</label>
                    <input class="slider-text" type="text" id="dues" size="8" />
                    <div id="dues_slider"></div><br>
                    
                    <label for="insurance">Annual insurance</label>
                    <input class="slider-text" type="text" id="insurance" size="8" />
                    <div id="insurance_slider"></div><br>
                    
                    <label for="appreciation_rate">Annual appreciation</label>
                    <input class="slider-text" type="text" id="appreciation_rate" size="8" />
                    <div id="appreciation_rate_slider"></div><br>
                    
                    <label for="income_tax_rate">Marginal income tax</label>
                    <input class="slider-text" type="text" id="income_tax_rate" size="8" />
                    <div id="income_tax_rate_slider"></div><br>
                    
                    <label for="inflation_rate">Inflation</label>
                    <input class="slider-text" type="text" id="inflation_rate" size="8" />
                    <div id="inflation_rate_slider"></div><br>
                     
                    <label for="mortage">Monthly mortage</label>
                    <input type="text" id="mortage" value="" style="color:green" disabled><br>
                    
                    <br><hr><br>
 
                    <label for="rent">Rent</label>
                    <input class="slider-text" type="text" id="rent" size="8" />
                    <div id="rent_slider"></div><br>
                    
                    <label for="rent_inflation_rate">Rental inflation</label>
                    <input class="slider-text" type="text" id="rent_inflation_rate" size="8" />
                    <div id="rent_inflation_rate_slider"></div><br>
                    
                    <label for="return_cash_rate">Return on cash</label>
                    <input class="slider-text" type="text" id="return_cash_rate" size="8" />
                    <div id="return_cash_rate_slider"></div><br>
                    
          </fieldset>
          
     </div><!--parameters-->
          
     <div class="graph" id="graph1">
          <h3 class="graph-title">Value</h3>
     </div>
     <div class="graph" id="graph2">
          <h3 class="graph-title">Payment</h3>
     </div>
     
     <div id="summary">
          <h3 class="table-title">Cost-Benefit Analysis</h3>
          <table>
               <caption align="bottom">
               </caption>
               <colgroup>
                    <col class="summary-col" />
                    <col class="summary-col" />
               </colgroup>
               <thead>
                    <tr>
                         <th scope="col">Item</th>
                         <th scope="col">Value ($)</th>
                    </tr>
               </thead>
               <tbody>
                    <tr>
                         <td>Total home value</td>
                         <td id="total-value"></td>
                    </tr>
                    <tr>
                         <td>Total debt</td>
                         <td id="total-debt"></td>
                    </tr>
                         <tr>
                         <td>Total equity</td>
                         <td id="total-equity"></td>
                    </tr>
                    </tr>
                         <tr>
                         <td>Transaction cost</td>
                         <td id="total-transaction"></td>
                    </tr>
                    <tr>
                         <td>Net cash from sale</td>
                         <td id="total-net"></td>
                    </tr>
                         <tr>
                         <td>Total savings (rent)</td>
                         <td id="total-savings"></td>
                    </tr>
                    <tr>
                         <td class="benefit">Benefit of owning</td>
                         <td id="total-benefit" class="benefit"></td>
                    </tr>                    
               </tbody>
          </table>
     </div><!--summary-->
     <span id="clear-both"></span><br>
          
</div><!--rentbuy container-->

<div id="economie-blurb">
    <h4>Notes:</h4>	
    <ol>
	<li>"monthly mortgage": The geometric series calculation is slightly different from the one <a href="https://www.khanacademy.org/economics-finance-domain/core-finance/housing/mortgages-tutorial/v/geometric-series-sum-to-figure-out-mortgage-payments">described</a></li>
	<li>"savings": The savings from renting compared to buying. That is, difference (renting - buying) is included in this value</li>
	<li>"purchase": This includes inflation corrected maintenance, dues, and insurance</li>
	<li>"Transaction cost": Fixed at 6% of the total home value</li>
    </ol>
    <h4>Credits:</h4>	
    <p id="credit">
	The inspiration and model for this page is taken directly from the wonderful work of the <a href="https://www.khanacademy.org/economics-finance-domain/core-finance/housing/renting-v-buying/v/renting-vs--buying-a-home">
	Khan Adademy</a> section on finance. Download the <a href="data/buyrent.ods" target="_blank">spreadsheet</a> that I obtained from the website to see the modelling
	calculations, assumptions, and approximations.  
    </p>    
</div>

{% endblock content %}

templates/mousy/household.html
{% extends 'mousy/base.html' %}
{% block head %}

    <!-- Add crossfilter library -->
    <script type="text/javascript" src="/static/mousy/js/crossfilter.js"></script>
        
    <!--Add dc.js library -->
    <script type="text/javascript" src="/static/mousy/js/dc.js"></script>
    <link rel="stylesheet" type="text/css"  href="/static/mousy/css/dc.css" />
    
    <!--Add Bootstrap library -->
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css"  />
  
    <title>Mousy{% block title %} | {{ title }}{% endblock title %}</title>
 
    <script type="text/javascript" src="/static/mousy/js/household.js"></script>
    
{% endblock head %}

{% block content %}     

     <h4><a id="add-receipt" href="/household/receipt/add/">Add New Receipt (login required)</a></h4>                

    <div class='container' id='main-container'>
        <div class='content'>
            <div class='container'>
               <div class='row'>
                    <div class='span6' id='dc-day-chart'>
                        <h4>Daily Expenses</h4>
                        
                    </div>
                </div>
                
                <div class='row'>
                    <div class='span6' id='dc-month-chart'>
                        <h4>Monthly Expenses</h4>
                        
                    </div>
                    <div class='span6' id='dc-who-chart'>
                        <h4>Expenses by user</h4>
                        
                    </div>                    
                </div>
                <br>
                <br>
                <div class='row'>
                    <div class='span12' id='table-chart'>
                        <h4>Expense Details</h4>
                        <table class="table table-hover" id="dc-table-graph">
                            <thead>
                                <tr class="header">
                                    <th>Date</th>
                                    <th>Amount</th>
                                    <th>Detail</th>
                                    <th>Who</th>                                
                                </tr>                            
                            </thead>                        
                        </table>
                
                    </div>    
                </div>            
                
            </div>
        </div>
    </div>
    
{% endblock content %}